svc_profile_change_mail_start:
  path: /cm/
  controller: Svc\ProfileBundle\Controller\ChangeMailController::startForm

svc_profile_change_mail_sent1:
  path: /cm/mail1_sent/
  controller: Svc\ProfileBundle\Controller\ChangeMailController::mail1Sent


svc_profile_change_mail_activate:
  path: /cm/activate
  controller: Svc\ProfileBundle\Controller\ChangeMailController::activateNewMail

svc_profile_change_pw_start:
  path: /cpw/
  controller: Svc\ProfileBundle\Controller\ChangePWController::startForm
