services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Svc\ProfileBundle\Controller\ChangeMailController:
  Svc\ProfileBundle\Service\ChangeMailHelper:
  Svc\ProfileBundle\Controller\ChangePWController:
  Svc\ProfileBundle\Repository\UserChangesRepository:
    tags:
      - doctrine.repository_service
